---
- name: c
  apt:
    state: present
    pkg:
      - gcc
      - gdb

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /opt/libc-manual 
    - /opt/gnu-manual

- name: gnu reference docs
  command: curl -o /opt/gnu-manual/gnu-c-manual.html https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html

- name: libc reference docs
  unarchive:
    src: https://www.gnu.org/software/libc/manual/html_node/libc-html_node.tar.gz
    dest: /opt/libc-manual
    remote_src: true # to get it to download from the internet

- name: register docs
  block:
    - ansible.utils.update_fact:
        updates:
        - path: "lang_docs['gnu c manual']"
          value:
            name: GNU manual
            id: gnu_manual
            path: /opt/gnu-manual
            index: gnu-c-manual.html
        - path: "lang_docs['glibc manual']"
          value:
            name: GNU c library (glibc) manual
            id: libc_manual
            path: /opt/libc-manual/libc
            index: index.html
      register: updated
    - set_fact:
        lang_docs: "{{ updated.lang_docs }}"