---
- name: cpp
  apt:
    state: present
    pkg:
      - g++
      - stl-manual      # 2.5mb
      - unzip # for dealing with docs

# From https://en.cppreference.com/w/Cppreference:Archives
- name: create directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /icpc/documentation/cpp/cppreference-docs
    - /icpc/documentation/cpp/libc-manual
    

- name: libc reference docs
  unarchive:
    src: https://www.gnu.org/software/libc/manual/html_node/libc-html_node.tar.gz
    dest: /icpc/documentation/cpp/libc-manual
    remote_src: true # to get it to download from the internet
    
    


