---
- name: install dart repo key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 7FAC5991
- name: install dart repo
  apt_repository:
    repo: "deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main"
    state: present
    filename: 'google-dart'
- name: install dart
  apt: pkg=dart state=present
