---
- name: Python 3
  apt:
    state: present
    pkg:
      - python3
      - pypy3
      - python3-doc # 37.2 mb
      - pypy3-doc # 5mb
      - python-is-python3

- name: ipython
  apt:
    state: present
    install_recommends: false # it's like 500MB with recommends vs 14MB without
    pkg:
      - ipython3
     
- name: Create a directory to store the Documentation for python
  file:
    path: /icpc/documentation/python
    state: directory

- name: Copy the documentation for python
  copy:  src=files/documentation/python/ dest=/icpc/documentation/python/
