---
- name: check current timezone
  shell: cat /etc/timezone
  register: current_timezone

- name: set timezone
  copy: content={{ icpc_timezone }}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  when: current_timezone.stdout != icpc_timezone
  notify:
      - update timezone
