---
#  - name: apt repo for java
#    apt_repository: repo='ppa:webupd8team/java'
#    environment: '{{proxy_env}}'
#
#  - name: ppa for backported packages mostly
#    apt_repository: repo='ppa:kj42/icpc' state=present
#
#  - name: preseed java7 license acceptance
#    debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
#  - name: preseed java8 license acceptance
#    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  - name: install our compilers and tools
    apt: pkg={{ item }} state=present
    # environment: '{{proxy_env}}'
    with_items:
        - build-essential           # c/c++
        - ghc                       # haskell
        - fpc                       # pascal
        - python                    # python 2.7
        - python3                   # python 3
        - pypy                      # pypy python compiler
        - gnat                      # gnu ada
        - gfortran                  # fortran
        - mono-complete             # c#
        - fsharp                    # fsharp
        - lua5.2                    # lua
        #- oracle-java7-installer   # java7
        #- oracle-java8-installer    # java8
        - openjdk-8-jdk             # jdk8
        - gccgo                     # go reference compiler
        - golang                    # go using gcc
        - ruby                      # ruby
        - nodejs                    # javascript
        - gdc                       # D
        - scala                     # Scala
        - rustc                     # Rust
        - ocaml-nox                 # OCaml (~220mb)

  - name: install apt-transport-https so we can install dart
    apt: pkg="apt-transport-https" state=present

  - name: install dart repo key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      id: 7FAC5991

  - name: install dart repo
    apt_repository:
      repo: "deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main"
      state: present
      filename: 'google-dart'

  - name: install dart
    apt: pkg=dart state=present

  - name: add dart to path
    copy: dest=/etc/profile.d/dart_path.sh src=files/dart_path.sh

  - name: install kotlin
    unarchive: src=files/kotlin-compiler-1.1.4-3.zip dest=/opt creates=/opt/kotlinc

  - name: add kotlin to path
    copy: dest=/etc/profile.d/kotlin_path.sh src=files/kotlin_path.sh

  # Frees up around 375mb
#  - name: remove jdk files that we downloaded
#    file: path={{item}} state=absent
#    with_items:
#      - /var/cache/oracle-jdk7-installer
#      - /var/cache/oracle-jdk8-installer

#  - name: check for scala
#    stat: path=/usr/bin/scala
#    register: has_scala

#  - name: get scala deb file
#    #copy: src=files/scala.deb dest=/tmp/scala.deb
#    get_url: url=http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb dest=/tmp/scala.deb
#    when: not has_scala.stat.exists and scala_deb_url is undefined

#  - name: get scala deb file
#    get_url: url={{scala_deb_url}} dest=/tmp/scala.deb
#    when: not has_scala.stat.exists and scala_deb_url is defined

#  - name: install scala
#    apt: deb=/tmp/scala.deb
#    when: not has_scala.stat.exists

#  - name: remove some bits of the scala docs we probably don't need
#    file: path={{item}} state=absent
#    with_items:
#      - /usr/share/doc/scala/api/scala-compiler
#      - /usr/share/doc/scala/api/scala-reflect
#      - /tmp/scala.deb
