---
  - name: install generic/common development tools
    apt:
      state: present
      pkg:
        - vim       
        - gedit     # Simple gnome text editor w/ syntax highlighting

  - name: install vscode
    when: "'vscode' in devtools"
    include_tasks: 'devel_tools/vscode.yml'