---
  - name: apt repo for (github) atom
    apt_repository: repo='ppa:webupd8team/atom' update_cache=yes
  - name: apt repo for IntelliJ IDEA
    apt_repository: repo='ppa:mmk2410/intellij-idea' update_cache=yes
    # environment: '{{proxy_env}}'
  - name: install tools
    apt: pkg={{ item }} state=present
    # environment: '{{proxy_env}}'
    with_items:
        - atom           # Text editor from github
        - vim-gnome      # graphical vim
        - emacs          # emacs(with x)
        - gedit          # Simple gnome text editor w/ syntax highlighting
        # Monodevelop and friends: 140mb
        - monodevelop
        #- monodevelop-debugger-gdb
        - gdb
        # codeblocks: 92mb
        - codeblocks
        - codeblocks-contrib
        # netbeans --noinstall-recommends: 175mb(440mb otherwise)
        #- netbeans
        - geany
        - geany-plugins
        - jq
        - intellij-idea-community   # IntelliJ IDEA community
