---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Pull domjudge image
  docker_image:
    name: domjudge/judgehost:latest
    source: pull

- name: Force cgroup v1
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0 biosdevname=0 consoleblank=0 net.ifnames=0"'
    backup: yes

- name: Update GRUB configuration
  command: update-grub
