---
  - name: install eclipse(64bit)
    unarchive: src=files/eclipse-java-2019-06-R-linux-gtk-x86_64.tar.gz dest=/opt creates=/opt/eclipse

  - name: eclipse shortcut
    copy: src=files/eclipse/Eclipse.desktop dest=/usr/share/applications/Eclipse.desktop

  # Eclipse plugins(for c/c++ and python)
  - name: install cdt plugin
    shell: |
      /opt/eclipse/eclipse -nosplash \
          -application org.eclipse.equinox.p2.director \
          -repository http://download.eclipse.org/tools/cdt/releases/9.8,http://download.eclipse.org/releases/2019-06/ \
          -destination /opt/eclipse \
          -installIU org.eclipse.cdt.feature.group \
          -installIU org.eclipse.cdt.platform.feature.group | grep -v DEBUG

  - name: install pydev plugin
    shell: |
      /opt/eclipse/eclipse -nosplash \
          -application org.eclipse.equinox.p2.director \
          -repository http://pydev.org/updates/ \
          -destination /opt/eclipse \
          -installIU org.python.pydev.feature.feature.group | grep -v DEBUG

  # This is somewhat large, ~750mb
  #- name: eclipse recommenders
  #  unarchive: src=files/eclipse/eclipse-recommenders-neon.zip dest=/opt creates=/opt/eclipse-recommenders

  # See this for how to set global eclipse configurations
  - name: configure eclipse
    copy: src=files/eclipse/eclipse_plugincustomization.ini dest=/opt/eclipse/eclipse_plugincustomization.ini
  - name: fixup the eclipse.ini file to use our custom configuration
    lineinfile: dest=/opt/eclipse/eclipse.ini insertafter="-vmargs" line="-Declipse.pluginCustomization=/opt/eclipse/eclipse_plugincustomization.ini"
