---
- name: install xfce
  apt:
    state: present
    pkg:
      - xserver-xorg
      - xfce4
      - lightdm
      - lightdm-gtk-greeter   # This keeps us from installing unity-greeter, which would pull in unity-settings and ibus(which breaks ctrl+space autocomplete in eclipse)
      - xfce4-power-manager
      - xubuntu-default-settings
      - xfce4-terminal
      - firefox
      - alacarte # menu editor
      - mupdf # lighweight pdf viewer

- name: Remove unneeded packages
  apt:
    state: absent
    purge: yes
    pkg:
      - byobu
      - xscreensaver
      - xscreensaver-data
      - yelp
      - desktop-base
      - vlc-data

- name: setup lightdm
  copy: src=files/lightdm.conf dest=/etc/lightdm/lightdm.conf

- name: configure xorg/x11
  copy: src=files/xorg.conf dest=/etc/X11/xorg.conf
