---
- name: install docs
  apt:
    state: present
    pkg:
      - python-doc      # 32 mb
      - python3-doc     # 37.2 mb
      - stl-manual      # 2.5mb
      - fp-docs         # 32mb
      - openjdk-11-doc   # 246 mb
      - openjdk-11-source   # 60 mb
      - ghc-doc         # 146 mb
      - monodoc-browser # 80mb
      - scala-doc       # 413mb somehow

- name: create simple index page for links to docs
  copy: src=files/language-docs.html dest=/opt/localwww/index.html

- name: create symlinks to docs
  file: state=link src={{item.src}} dest=/opt/localwww/{{item.dest}}
  with_items:
    - src: '/usr/share/doc/stl-manual/html/'
      dest: 'stl-doc'
    - src: '/usr/share/doc/openjdk-11-doc/api/'
      dest: 'java-doc'
    - src: '/usr/share/doc/scala-2.11/api/library/'
      dest: 'scala-doc'
    - src: '/usr/share/doc/python-doc/html/'
      dest: 'py2-doc'
    - src: '/usr/share/doc/python3-doc/html/'
      dest: 'py3-doc'
    - src: '/usr/share/doc/fp-docs/3.0.4/'
      dest: 'fpc-doc'
    - src: '/usr/share/doc/ghc-doc/'
      dest: 'haskell-doc'
