---
- name: make sure web dir exists
  file: state=directory path=/opt/localwww

- name: add simple-httpd init script
  copy: src=files/simple-httpd-upstart.conf dest=/etc/init/simple-httpd.conf
  notify: restart simple-httpd
