---
- name: install autossh
  apt: pkg=autossh state=present

- name: create ssh tunnel user
  user: name=jumpy state=present system=yes

- name: create .ssh directory
  file: dest=/home/jumpy/.ssh state=directory

- name: set up private key
  copy:
    content: "{{ jumpbox_key }}"
    mode: 0400
    owner: jumpy
    group: jumpy
    dest: /home/jumpy/.ssh/id_ed25519

- name: set up authorized key for someone to log in to this team machine over the reverse tunnel
  authorized_key:
    user: "{{ item }}"
    key: "{{ jumpbox_authorized_key }}"
  with_items:
    - root
    - icpcadmin

- name: create autossh service
  template: src=files/autossh.service.j2 dest=/etc/systemd/system/autossh.service

- name: enable autossh service
  service: enabled=yes name=autossh

- name: make sure ssh is enabled
  service: enabled=yes name=ssh
