---
- name: disable udev persistent net generator
  file: state=link name=/etc/udev/rules.d/75-persistent-net-generator.rules src=/dev/null

- name: disable console blanking
  lineinfile: dest=/etc/default/grub regexp="^GRUB_CMDLINE_LINUX_DEFAULT" line='GRUB_CMDLINE_LINUX_DEFAULT="biosdevname=0 consoleblank=0"' state=present
  notify: update grub

- name: journald write to /dev/tty1
  copy: src=files/systemd-journald.conf dest=/etc/systemd/journald.conf

- name: systemd disable status messages on console
  copy: src=files/systemd-system.conf dest=/etc/systemd/system.conf
